books/urls.py
from django.conf.urls import patterns, url
from books import views

urlpatterns = [
    url(r'^$', views.BooksModelView.as_view(), name='index'),
    url(r'^book/$', views.AuthorList.as_view(), name='book_list'),
    url(r'^author/$', views.AuthorList.as_view(), name='author_list'),
    url(r'^publisher/$', views.PublisherList.as_view(), name='publisher_list'),
    url(r'^book/(?P<pk>\d+)/$', views.BookDetail.as_view(), name='book_detail'),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorDetail.as_view(), name='author_detail'),
    url(r'^publisher/(?P<pk>\d+)/$', views.PublisherDetail.as_view(), name='publisher_detail'),
]

crawler/urls.py
from django.conf.urls import patterns, url
from crawler import views
from mysite import settings
urlpatterns = [
    url(r'^$', views.CrawlerMainView.as_view(), name='main'),
    url(r'^new_crawl/coupang/ecommerce_list$', views.NewCrawlEcommerceListView.as_view(), name='new_crawl_ecommerce_list'),
    url(r'^new_crawl/coupang/ecommerce_review$', views.NewCrawlEcommerceReviewView.as_view(), name='new_crawl_ecommerce_review'),
    url(r'^ecommerce_list/coupang/(?P<category>\S+)/$', views.CrawlerListView.as_view(), name='ecommerce_list'),
    url(r'^ecommerce_review/coupang/(?P<uid>\d+)/$', views.CrawlerReviewView.as_view(), name='ecommerce_review'),
]

mysite/urls.py
#-*- coding: utf-8 -*-
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView # 뷰를 따로 안만들어도 이미 만들어진 html로 접속할 수 있음
from django.views.generic import RedirectView # 원하는 url로 리다이렉트
from mysite import views
from django.conf.urls import url, patterns

urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name='mysite/index.html'), name='home'),
    #url(r'^$', RedirectView.as_view(url='polls')),
    url(r'^admin/', admin.site.urls),
    #url(r'^polls/$', views.index, name='index'),
    #url(r'^polls/(?P<question_id>\d+)/$', views.detail, name='detail'),
    #url(r'^polls/(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    #url(r'^polls/(?P<question_id>\d+)/results/$', views.results, name='results')
    #url(r'', include('polls.urls', namespace="polls")),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^crawler/', include('crawler.urls', namespace="crawler")),
]

crawler/models.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import smart_unicode
import datetime

# Create your models here.
class CrawlingSiteList(models.Model):
    rClass = models.CharField(max_length=30, default="site")
    message = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=10, default="READY")
    url = models.CharField(max_length=200)
    spiderName = models.CharField(max_length=30, default="")
    siteName = models.CharField(max_length=50)
    category = models.CharField(max_length=50, null=True, blank=True)
    latestCrawlTime = models.DateTimeField(default=datetime.datetime.today)

    def __unicode__(self):
        return u'siteName : %s, spiderName : %s, category : %s' %(self.siteName, self.spiderName, self.category)
        # return smart_unicode(self.title)

class EcommerceListItem(models.Model):
    rClass = models.CharField(max_length=30, default="ecommlist")
    message = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=10, default="ok")
    crawlTime = models.DateTimeField(default=datetime.datetime.today)
    uid = models.CharField(max_length=30, primary_key=True)
    category = models.CharField(max_length=20, null=True, blank=True)
    linkUrl = models.CharField(max_length=100, null=True, blank=True)
    createTime = models.DateTimeField(default=datetime.datetime.today)
    refCount = models.PositiveIntegerField(null=True, blank=True)
    reviewCount = models.PositiveIntegerField()
    writerId = models.CharField(max_length=30, null=True, blank=True)
    writerName = models.CharField(max_length=30, null=True, blank=True)
    title = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    rawData = models.TextField(null=True, blank=True)
    price = models.PositiveIntegerField(null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)
    totalCount = models.PositiveIntegerField(null=True, blank=True)
    agreeCount = models.PositiveIntegerField(null=True, blank=True)
    refuseCount = models.PositiveIntegerField(null=True, blank=True)

    def __unicode__(self):
        return u'title : %s, status : %s ' %(self.title, self.status)
        # return smart_unicode(self.title)

class EcommerceReviewItem(models.Model):
    rClass = models.CharField(max_length=30, default="ecommreview")
    message = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=10, default="ok")
    uid = models.ForeignKey(EcommerceListItem, on_delete=models.CASCADE)
    reviewId = models.CharField(max_length=30, primary_key=True)
    writerId = models.CharField(max_length=30, null=True, blank=True)
    writerName = models.CharField(max_length=30, null=True, blank=True)
    title = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)
    crawlTime = models.DateTimeField(default=datetime.datetime.today)
    createTime = models.DateTimeField(default=datetime.datetime.today)
    commentCount = models.PositiveIntegerField(null=True, blank=True)
    refCount = models.PositiveIntegerField(null=True, blank=True)
    totalCount = models.PositiveIntegerField(null=True, blank=True)
    agreeCount = models.PositiveIntegerField(null=True, blank=True)
    refuseCount = models.PositiveIntegerField(null=True, blank=True)

    def __unicode__(self):
        return u'title : %s, status : %s ' %(self.title, self.status)
        # return smart_unicode(self.title)

crawler/forms.py
from django import forms

class KeywordForm(forms.Form):
    keyword = forms.CharField(max_length=100, widget=forms.TextInput)
    def test(self):
        pass

crawler/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404, render, render_to_response, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import View, TemplateView, ListView
from .models import EcommerceListItem, CrawlingSiteList, EcommerceReviewItem

import commands
import urllib2, re

def convert_category(category):
    if category == u'출산/유아동':
        category='94404'
    elif category == u'반려/애완용품':
        category='41853'
    elif category == u'반려/애완용품':
        category='41853'
    elif category == u'식품':
        category='41563'
    elif category == u'뷰티':
        category='108460'
    else:
        category=None
    return category

# Create your views here.
class CrawlerMainView(TemplateView):
    model = CrawlingSiteList
    template_name = 'crawler/index.html'
    success_url = template_name

    def get_context_data(self, **kwargs):
        context = super(CrawlerMainView, self).get_context_data(**kwargs)
        context['object_list'] = CrawlingSiteList.objects.all()
        print CrawlingSiteList.objects.all()
        return context

class NewCrawlEcommerceListView(View):
    model = CrawlingSiteList

    def post(self, request, *args, **kwargs):
        print request.POST
        keyword = request.POST['keyword']
        if not keyword or keyword == '' or len(re.findall('\s+', keyword)) > 1:
            ## 작업 추가..
            print 'error'
            return HttpResponseRedirect(reverse('crawler:main'))
        else:
            category = convert_category(request.POST['category'])
            cmd = u'curl http://localhost:6800/schedule.json -F project=MAScrapper -F spider=coupanglist -F setting=DOWNLOAD_DELAY=30 -F category={category} -F keyword={keyword}'.format(keyword=keyword, category=category)
            cmd = cmd.encode('utf8')
            failure, result = commands.getstatusoutput(cmd)
            if failure:
                print 'FAILED!'
            return HttpResponseRedirect(reverse('crawler:main'))

class NewCrawlEcommerceReviewView(View):
    model = EcommerceReviewItem

    def post(self, request, *args, **kwargs):
        print request.POST
        uid = request.POST['uid']
        if not uid or uid == '':
            ## 작업 추가..
            print 'error'
            return HttpResponseRedirect(reverse('crawler:main'))
        else:
            cmd = u'curl http://localhost:6800/schedule.json -F project=MAScrapper -F spider=coupangreview -F setting=DOWNLOAD_DELAY=30 -F uid={uid}'.format(uid=uid)
            cmd = cmd.encode('utf8')
            failure, result = commands.getstatusoutput(cmd)
            print "###"
            print failure
            print result
            print "###"
            if failure:
                print 'FAILED!'
            return HttpResponseRedirect(request.POST['previous'])

class CrawlerListView(TemplateView):
    model = EcommerceListItem
    template_name = 'crawler/ecommerce_list.html'

    def get_context_data(self, **kwargs):
        print kwargs
        category = kwargs['category']
        category = convert_category(category)
        context = super(CrawlerListView, self).get_context_data(**kwargs)
        #context['object_list'] = EcommerceListItem.objects.all()
        context['object_list'] = EcommerceListItem.objects.filter(category=category)
        return context

class CrawlerReviewView(TemplateView):
    model = EcommerceReviewItem
    template_name = 'crawler/ecommerce_review.html'

    def get_context_data(self, **kwargs):
        print '!!'
        uid = kwargs['uid']
        context = super(CrawlerReviewView, self).get_context_data(**kwargs)
        context['object_list'] = EcommerceReviewItem.objects.filter(uid_id=uid)
        return context

crawler/templates/crawler/ecommerce_list.html
{% extends "base.html" %}

{% block content %}
  <h2>Crawling List</h2>
  <li><a href="/crawler/ec">전부 수집하기</a><li>
  <table>
    <tr>
      <td>제품</td>
      <td>가격</td>
      <td>평점</td>
      <td>좋아요</td>
      <td>나빠요</td>
      <td>리뷰 갯수</td>
      <td>조회수</td>
      <td>uid</td>
      <td>크롤링시각</td>
      <td>게시물생성시각</td>
      <td>링크주소</td>
      <td>리뷰수집</td>
      <td>리뷰확인</td>
    </tr>
      {% for model in object_list %}
        <tr>
          <td>{{ model.title }}</td>
          <td>{{ model.price }}</td>
          <td>{{ model.rating }}</td>
          <td>{{ model.agreeCount }}</td>
          <td>{{ model.refuseCount }}</td>
          <td>{{ model.reviewCount }}</td>
          <td>{{ model.refCount }}</td>
          <td>{{ model.uid }}</td>
          <td>{{ model.crawlTime }}</td>
          <td>{{ model.createTime }}</td>
          <td>{{ model.linkUrl }}</td>
          <form action="{% url 'crawler:new_crawl_ecommerce_review' %}" method="post">
          {% csrf_token %}
          <input type="hidden" value="{{ request.path }}" name="previous">
          <input type="hidden" value="{{ model.uid }}" name="uid">
          <td><button>수집</button></td>
          </form>
          <td><li><a href="/crawler/ecommerce_review/coupang/{{ model.uid }}">확인</a></li></td>
        </tr>
      {% endfor %}
  </table>
{% endblock content %}

crawler/templates/crawler/ecommerce_review.html
{% extends "base.html" %}

{% block content %}
  <h2>Crawling Review Data</h2>
  <table>
    <tr>
      <td>상품ID</td>
      <td>리뷰ID</td>
      <td>작성자ID</td>
      <td>이름</td>
      <td>제목</td>
      <td>내용</td>
      <td>평점</td>
      <td>좋아요</td>
      <td>나빠요</td>
      <td>조회수</td>
      <td>댓글수</td>
      <td>크롤링시각</td>
      <td>게시물생성시각</td>
      <td>댓글확인</td>
    </tr>
      {% for model in object_list %}
        <tr>
          <td>{{ model.uid_id }}</td>
          <td>{{ model.reviewId }}</td>
          <td>{{ model.writerId }}</td>
          <td>{{ model.writerName }}</td>
          <td>{{ model.title }}</td>
          <td>{{ model.content }}</td>
          <td>{{ model.rating }}</td>
          <td>{{ model.agreeCount }}</td>
          <td>{{ model.refuseCount }}</td>
          <td>{{ model.refCount }}</td>
          <td>{{ model.commentCount }}</td>
          <td>{{ model.crawlTime }}</td>
          <td>{{ model.createTime }}</td>
          <td><button>보기</button></td>
          </form>
        </tr>
      {% endfor %}
  </table>
{% endblock content %}

crawler/templates/crawler/index.html
{% extends "base.html" %}

{% block content %}
  {% load staticfiles %}
  <script type="text/javascript" src="{% static "crawler/js/nullcheck.js" %}"></script>
  <h2>Crawling Site List</h2>
  <table>
    <tr>
      <td>상태</td>
      <td>사이트명</td>
      <td>카테고리</td>
      <td>기본주소</td>
      <td>최신수집일</td>
      <td>수집</td>
      <td>결과</td>
    </tr>
    {% for model in object_list %}
    <tr>
      <td>{{ model.status }}</td>
      <td>{{ model.siteName }}</td>
      <form action="{% url 'crawler:new_crawl_ecommerce_list' %}" method="post">
      {% csrf_token %}
      <td>{{ model.category }}</td>
      <td>{{ model.url }}</td>
      <td>{{ model.latestCrawlTime }}</td>
      <input type="hidden" name="category" value="{{ model.category }}">
      <td><input type="text" name="keyword" value="" id="txtInput"></td>
      </form>
      <td><li><a href="/crawler/ecommerce_list/coupang/{{ model.category }}/">확인</a></td>
    </tr>
    {% endfor %}
  </table>
{% endblock content %}